export const datosConductores: Record<string, ConductorData> = {
    'H07V': {
        nombre: 'H07V-U / H07V-R / H07V-K',
        caracteristicas: 'Conductor eléctrico unipolar, construido de cobre recocido, desnudo o recubierto  de una capa metálica; sólido clase 1, cableado clase 2, flexible clase 5, con aislación de policloruro de vinilo PVC/C.',
        uso: 'Apto para ser instalado en ductos y molduras o bandejas tipo liviana en ambiente seco. En circuitos de baja tensión en instalaciones fijas.',
        tempMax: '70 °C',
        tension: '450/750 V',
        aislamiento: 'PVC',
        cubierta: 'No tiene',
        tabla_ref: '70C'
    },
    'H07Z1': {
        nombre: 'H07Z1-U / H07Z1-R / H07Z1-K',
        caracteristicas: 'Conductor eléctrico unipolar aislado, sin cubierta, no propagador del incendio, libre de halógenos y con baja emisión de humos y gases corrosivos cuando están expuestos al fuego; construido de cobre recocido, desnudo o recubierto de una capa metálica; sólido clase 1, cableado clase 2 y flexible clase 5, con aislación de material termoplástico del tipo TI 7.',
        uso: 'Apto para ser usado en lugares de reunión de personas. Puede ser instalado en ductos y molduras o bandejas tipo liviana. En circuitos de baja tensión en instalaciones fijas, en ambiente seco. No Puede ser utilizados como alimentador, ni subalimentador.',
        tempMax: '70 °C',
        tension: '450/750 V',
        aislamiento: 'Termoplástico libre de halógenos, retardante a la llama, de baja emisión de humos',
        cubierta: 'No tiene',
        tabla_ref: '70C'
    },
    'THHN': {
        nombre: 'THHN',
        caracteristicas: 'Conductor eléctrico unipolar, construido con cobre recocido, cableado, compactado o comprimido; con aislación de policloruro de vinilo PVC, con cubierta o chaqueta de nylon.',
        uso: 'Apto para ser instalado en ductos, molduras y bandejas (solo tipo THHN/TC a partir del calibre 1/0 AWG). En ambientes secos. La cubierta lo hace resistente a la acción de aceites, grasas, ácidos y gasolina.',
        tempMax: '90 °C',
        tension: '600 V',
        aislamiento: 'PVC',
        cubierta: 'Nylon o similar',
        tabla_ref: '90C'
    },
    'THWN-2': {
        nombre: 'THWN-2',
        caracteristicas: 'Conductor eléctrico unipolar, construido con cobre recocido, cableado, compactado ó comprimido; con aislación de policloruro de vinilo PVC, con cubierta o chaqueta de nylon.',
        uso: 'Apto para ser instalado en ductos, molduras y bandejas (solo tipo THHN/TC a partir del calibre 1/0 AWG). En ambientes secos y húmedos. La cubierta lo hace resistente a la acción de aceites, grasas, ácidos y gasolina.',
        tempMax: '90 °C',
        tension: '600 V',
        aislamiento: 'PVC',
        cubierta: 'Nylon o similar',
        tabla_ref: '70C'
    },
    'THWN': {
        nombre: 'THWN',
        caracteristicas: 'Conductor eléctrico unipolar, construido con cobre recocido, cableado, compactado ó comprimido; con aislación de policloruro de vinilo PVC, con cubierta o chaqueta de nylon.',
        uso: 'Apto para ser instalado en ductos, molduras y bandejas (solo tipo THHN/TC a partir del calibre 1/0 AWG). En ambientes secos y húmedos. La cubierta lo hace resistente a la acción de aceites, grasas, ácidos y gasolina.',
        tempMax: '75 °C',
        tension: '600 V',
        aislamiento: 'PVC',
        cubierta: 'Nylon o similar',
        tabla_ref: '70C'
    },
    'RV': {
        nombre: 'RV',
        caracteristicas: 'Conductor eléctrico unipolar o multipolar, sin armadura ni pantalla; construido de cobre recocido, desnudo o recubierto de una capa metálica; sólido clase 1 o cableado clase 2 cableado, con aislación de polietileno reticulado (XLPE) y cubierta termoplástica de cloruro de polivinilo (PVC) tipo ST2.',
        uso: 'Apto para ser instalado en ductos, en bandejas, en canastillo, en escalerillas (solo tipo /TC) y al aire libre. En circuitos de distribución en baja tensión, como alimentador o subalimentador.',
        tempMax: '90 °C',
        tension: '600/1000 V',
        aislamiento: 'XLPE',
        cubierta: 'PVC',
        tabla_ref: '90C'
    },
    'RV-K': {
        nombre: 'RV-K',
        caracteristicas: 'Conductor eléctrico unipolar o multipolar, sin armadura ni pantalla; construido de cobre recocido, desnudo o recubierto de una capa metálica; flexible clase 5, con aislación de polietileno reticulado (XLPE) y cubierta termoplástica de cloruro de polivinilo (PVC) designación ST2.',
        uso: 'Apto para ser instalado directamente enterrado, en ductos, en bandejas,en canastillo, en escalerillas (solo tipo /TC) y al aire libre. En circuitos de distribución en baja tensión, como alimentador o subalimentador flexible para tendido fijo.',
        tempMax: '90 °C',
        tension: '600/1000 V',
        aislamiento: 'XLPE',
        cubierta: 'PVC',
        tabla_ref: '90C'
    },
    'RZ1': {
        nombre: 'RZ1',
        caracteristicas: 'Conductor eléctrico unipolar o multipolar, sin armadura ni pantalla, retardante a la llama, no propagador de incendio, con baja emisión de gases tóxicos, baja opacidad de humos y bajo índice de acidez de los gases de combustión; construido de cobre recocido, desnudo o recubierto de una capa metálica; cableado, con aislación de polietileno reticulado (XLPE) y cubierta de material termoplástico tipo ST8, libre de halógenos.',
        uso: 'Apto para ser usado en lugares de reunión de personas.Puede ser instalado en ductos, en bandejas, en escalerillas en canastillo, al aire libre y subterráneo. En circuitos de distribución en baja tensión, como alimentador o subalimentador.',
        tempMax: '90 °C',
        tension: '600/1000 V',
        aislamiento: 'XLPE',
        cubierta: 'Termoplástico libre de halógenos, retardante a la llama, de baja emisión de humos.',
        tabla_ref: '90C'
    },
    'RZ1-K': {
        nombre: 'RZ1-K',
        caracteristicas: 'Conductor eléctrico unipolar o multipolar, sin armadura ni pantalla,retardante a la llama, no propagador de incendio, con baja emisión de gases tóxicos, baja opacidad de humos y bajo índice de acidez de los gases de combustión; construido de cobre recocido, desnudo o recubierto de una capa metálica; flexible clase 5, con aislación de polietileno reticulado (XLPE) y cubierta de material termoplástico tipo ST8, libre de halógenos.',
        uso: 'Apto para ser usado en lugares de reunión de personas. Puede ser instalado en ductos, en bandejas, en escalerillas, en canastillo, al aire libre y subterráneo. En circuitos de distribución en baja tensión, como alimentador o subalimentador flexible para instalación fija.',
        tempMax: '90 °C',
        tension: '600/1000 V',
        aislamiento: 'XLPE',
        cubierta: 'Termoplástico libre de halógenos, retardante a la llama, de baja emisión de humos.',
        tabla_ref: '90C'
    },
    'RZ1-K(AS+)': {
        nombre: 'Rz1-k (AS+)',
        caracteristicas: 'Conductor eléctrico unipolar o multipolar, sin armadura ni pantalla, retardante a la llama, no propagador de incendio, resistente al fuego, con baja emisión de gases tóxicos, baja opacidad de humos y bajo índice de acidez de los gases de combustión; construido de cobre recocido, desnudo o recubierto de una capa metálica; flexible clase 5, con aislación de cinta de mica y polietileno reticulado (XLPE) y cubierta de material termoplástico tipo ST8, libre de halógenos',
        uso: 'Apto para instalaciones de equipos de seguridad que deban mantenerse en servicio durante un incendio y enlocales donde se requiera una baja emisión de humos y gases corrosivos en caso de incendio. Apto para instalaciones en lugares de reunión de personas. Puede ser instalado en ductos, en bandejas, en escalerillas, en canastillo, al aire libre y subterráneo. En circuitos de distribución en baja tensión, como alimentador o subalimentador flexible para instalación fija.',
        tempMax: '90 °C',
        tension: '600/1000 V',
        aislamiento: 'Cinta Mica + XLPE',
        cubierta: 'Termoplástico libre de halógenos, retardante a la llama, de baja emisión de humos.',
        tabla_ref: '90C'
    },
    'H03VV': {
        nombre: 'H03VV-F / H03VVH2-F',
        caracteristicas: 'Conductor eléctrico tipo cordón flexible; circular o plano, construido con 2 o 3 conductores de cobre recocido, desnudo o recubierto de una capa metálica; clase 5, con aislación de policloruro de vinilo PVC/D para temperatura de servicio de 70 ºC, con cubierta o revestimiento de PVC/ST5 y rango de voltaje de 300/300 volts.',
        uso: 'Apto para ser usado en instalaciones móviles domiciliarias y para alimentación de electrodomésticos con un esfuerzo mecánico ligero. Puede ser usado en interior, en recintos secos y/o húmedos (no apto para instalación fija o sumergido).',
        tempMax: '70 °C',
        tension: '300/300 V',
        aislamiento: 'PVC',
        cubierta: 'PVC',
        tabla_ref: 'movil'
    },
    'H05VV': {
        nombre: 'H05VV-F / H05VVH2-F',
        caracteristicas: 'Conductor eléctrico tipo cordón flexible, construido con 2, 3, 4 o 5 conductores de cobre recocido, desnudo o recubierto de una capa metálica; cableados, clase 5, con aislación de policloruro de vinilo PVC/D para temperatura de servicio de 70 ºC, con cubierta o revestimiento de PVC/ST5 y rango de voltaje de 300/500 volts.',
        uso: 'Apto para ser usado en instalaciones móviles domiciliarias y para alimentación de electrodomésticos con un esfuerzo mecánico medio. Puede ser usado en interior, en recintos secos y/o húmedos (no apto para instalaciones sumergidas).',
        tempMax: '70 °C',
        tension: '300/500 V',
        aislamiento: 'PVC',
        cubierta: 'PVC',
        tabla_ref: 'movil'
    },
    'H05RR': {
        nombre: 'H05RR-F',
        caracteristicas: 'Conductor eléctrico de formación tipo cordón flexible, construido con 2, 3, 4 o 5 conductores de cobre recocido, desnudo o recubierto de una capa metálica; cableados, clase 5, con aislación de compuesto de goma etileno-propileno o materiales equivalentes, tipo IE4; con cubierta o revestimiento de compuesto de goma tipo SE3.',
        uso: 'Apto para ser usado en dispositivos eléctricos ligeros que no estén sometidos a grandes tensiones mecánicas, equipos de mano, electrodomésticos de uso ligero. Puede ser usado en salas secas y húmedas. Solo uso temporal en el exterior.No apto para instalaciones industriales/comerciales o agrícolas. No indicado para alimentar herramientas eléctricas industriales.',
        tempMax: '60 °C',
        tension: '300/500 V',
        aislamiento: 'EPR, EPDM O similar',
        cubierta: 'EPR, EPDM O similar',
        tabla_ref: 'movil'
    },
    'H05RN': {
        nombre: 'H05RN-F',
        caracteristicas: 'Conductor eléctrico de formación tipo cordón flexible, construido con 2, 3, 4 o 5 conductores de cobre recocido, desnudo o recubierto de una capa metálica; cableados, clase 5, con aislación de compuesto de goma etileno-propileno o materiales equivalentes, tipo IE4; con cubierta o revestimiento de compuesto de policloropreno u otro elastómero sintético equivalente, tipo SE4.',
        uso: 'Apto para alimentar dispositivos ligeros de bajo estrés mecánico. Puede ser usado permanentemente en el exterior, con esfuerzo mecánico normal.',
        tempMax: '60 °C',
        tension: '300/500 V',
        aislamiento: 'EPR, EPDM O similar',
        cubierta: 'Neopreno O similar',
        tabla_ref: 'movil'
    },
    'H07RN': {
        nombre: 'H07RN-F',
        caracteristicas: 'Conductor eléctrico de formación tipo cordón flexible, construido con 2, 3, 4 o 5 conductores de cobre recocido, desnudo o recubierto de una capa metálica; cableados, clase 5, con aislación de compuesto de goma etileno-propileno o materiales equivalentes, tipo IE4; con cubierta o revestimiento de compuesto de policloropreno u otro elastómero sintético equivalente, tipo SE4.',
        uso: 'Apto para ser usado en equipos industriales en servicio móvil, para esfuerzo mecánico medio. Puede ser usado en ambiente seco o húmedo así como exteriores. Puede ser usado en instalaciones provisionales.',
        tempMax: '60 °C',
        tension: '450/750 V',
        aislamiento: 'EPR, EPDM O similar',
        cubierta: 'Neopreno O similar',
        tabla_ref: 'movil'
    },
    'NYIFY': {
        nombre: 'NYIFY',
        caracteristicas: 'Conductor eléctrico plano, construido con 2 o 3 conductores de cobre recocido sólidos, con aislación de PVC y cubierta de PVC para temperatura de servicio de 70 ºC, para un rango de voltaje de 380 volts máximo.',
        uso: 'Apto para ser usado en instalaciones domiciliarias en ambientes interiores, sobrepuesto, no necesitan ducto.',
        tempMax: '70 °C',
        tension: '380 V',
        aislamiento: 'PVC',
        cubierta: 'PVC',
        tabla_ref: '70C'
    },
    'STP': {
        nombre: 'STP-1 / STP-2',
        caracteristicas: 'Conductor eléctrico flexible; plano, construido con 2 o 3 conductores de cobre recocido, desnudo flexible, con aislación integral de policloruro de vinilo para temperatura de servicio de 70 ºC, para un rango de voltaje de 300 volts máximo.',
        uso: 'Apto para ser usado en instalaciones móviles domiciliarias con un esfuerzo mecánico ligero.No puede ser usado en circuitos de instalación fija interior o exterior, no debe ser engrapado o clavado a las estructuras sólidas de la instalación o edificación, no debe ser usado en extensiones para enchufes',
        tempMax: '70 °C',
        tension: '300 V',
        aislamiento: 'PVC',
        cubierta: 'No tiene',
        tabla_ref: 'movil'
    },
    'Acometidas': {
        nombre: 'Acometidas',
        caracteristicas: 'Conductor cableado o alambre de cobre de temple duro, clase 1, aislación de compuesto Polietileno extruido de color negro, y resistencia a la intemperie',
        uso: 'En servicios aéreos como líneas de distribución y en acometidas de empalme',
        tempMax: '75 °C',
        tension: '600 V',
        aislamiento: 'PE',
        cubierta: 'No tiene',
        tabla_ref: '70C'
    },
    'SF-1': {
        nombre: 'SF-1',
        caracteristicas: 'Conductor eléctrico unipolar, construido de cobre recocido, desnudo o estañado; sólido o 7 hebras, cableado clase B, con aislación de silicona y malla de fibra de vidrio.',
        uso: 'Cableado del Enclavamiento de Puertas de Montacargas, resistentes a las llamas y adecuados para una temperatura máxima de 200 °C',
        tempMax: '200 °C',
        tension: '300 V',
        aislamiento: 'Silicona para temperatura de 200 °C',
        cubierta: 'Malla fibra de vidrio',
        tabla_ref: 'SinTabla'
    },
    'SF-2': {
        nombre: 'SF-2',
        caracteristicas: 'Conductor eléctrico unipolar, construido de cobre recocido, desnudo o estañado; sólido o 7 hebras, cableado clase B, con aislación de silicona y malla de fibra de vidrio.',
        uso: 'Cableado del Enclavamiento de Puertas de Montacargas, resistentes a las llamas y adecuados para una temperatura máxima de 200 °C',
        tempMax: '200 °C',
        tension: '600 V',
        aislamiento: 'Silicona para temperatura de 200 °C',
        cubierta: 'Malla fibra de vidrio',
        tabla_ref: 'SinTabla'
    },
    'H1Z2Z2': {
        nombre: 'H1Z2Z2-K',
        caracteristicas: 'Cables para instalaciones solares fotovoltaicas que han sido diseñados para resistir las exigentes condiciones ambientales que se producen en cualquier tipo de instalación fotovoltaica, ya sea fija, móvil, sobre tejado o de integración arquitectónica, conductor de cobre electrolítico estañado, clase 5 flexible, aislación libre de halógenos, cubierta ignifugada, resistencia a los impactos, a las grasas y aceites, resistencia a abrasión, resistencia a temperaturas ambientales extremas, rayos ultravioletas y al agua, No propagación de la llama Resistencia a los ataques químicos, Temperatura mínima de servicio: -40ºC Temperatura máxima del conductor: 120ºC Temperatura máxima en cortocircuito: 250ºC (máximo 5 s)',
        uso: 'Cables flexibles aptos para servicios móviles y para instalación fija en tejado o de integración arquitectónica. Adecuados para la conexión entre paneles fotovoltaicos y desde los paneles al inversor de corriente continua a alterna. Nopuede ser usado en instalaciones Subterráneas.',
        tempMax: '90 °C',
        tension: '1800 V DC / 600 - 1000 V AC',
        aislamiento: 'Elastómero termoestable libre de halógenos (Z) o Goma libre de halógenos (tipo XLEVA según UL / tipo EI6 según TÜV)',
        cubierta: 'Elastómero termoestable libre de halógenos (Z) o Goma ignifugada (tipo XLEVA según UL / tipo EM8 según TÜV)',
        tabla_ref: 'SinTabla'
    }
};

export const tablasDeCalculo: Record<string, any[]> = {
    '70C': [{ temp: 70, seccion_mm2: 1.5, A1: 14, B1: 16, E: 19 },
    { temp: 70, seccion_mm2: 2.08, awg: 14, A1: 16, B1: 19, E: 22 },
    { temp: 70, seccion_mm2: 2.5, A1: 18, B1: 21, E: 24 },
    { temp: 70, seccion_mm2: 3.31, awg: 12, A1: 21, B1: 25, E: 30 },
    { temp: 70, seccion_mm2: 4, A1: 24, B1: 28, E: 31 },
    { temp: 70, seccion_mm2: 5.26, awg: 10, A1: 28, B1: 34, E: 38 },
    { temp: 70, seccion_mm2: 6, A1: 31, B1: 36, E: 43 },
    { temp: 70, seccion_mm2: 8.37, awg: 8, A1: 38, B1: 45, E: 53 },
    { temp: 70, seccion_mm2: 10, A1: 42, B1: 50, E: 60 },
    { temp: 70, seccion_mm2: 13.3, awg: 6, A1: 50, B1: 60, E: 71 },
    { temp: 70, seccion_mm2: 16, A1: 56, B1: 68, E: 80 },
    { temp: 70, seccion_mm2: 21.1, awg: 4, A1: 66, B1: 80, E: 91 },
    { temp: 70, seccion_mm2: 25, A1: 73, B1: 89, E: 101 },
    { temp: 70, seccion_mm2: 26.7, awg: 3, A1: 76, B1: 93, E: 106 },
    { temp: 70, seccion_mm2: 33.6, awg: 2, A1: 87, B1: 108, E: 122 },
    { temp: 70, seccion_mm2: 35, A1: 89, B1: 110, E: 126 },
    { temp: 70, seccion_mm2: 42.4, awg: 1, A1: 100, B1: 125, E: 142 },
    { temp: 70, seccion_mm2: 50, A1: 108, B1: 134, E: 153 },
    { temp: 70, seccion_mm2: 53.5, awg: "1/0", A1: 116, B1: 144, E: 165 },
    { temp: 70, seccion_mm2: 67.4, awg: "2/0", A1: 133, B1: 167, E: 191 },
    { temp: 70, seccion_mm2: 70, A1: 136, B1: 171, E: 196 },
    { temp: 70, seccion_mm2: 85, awg: "3/0", A1: 153, B1: 193, E: 222 },
    { temp: 70, seccion_mm2: 95, A1: 164, B1: 207, E: 238 },
    { temp: 70, seccion_mm2: 107.2, awg: "4/0", A1: 176, B1: 223, E: 257 },
    { temp: 70, seccion_mm2: 120, A1: 188, B1: 239, E: 276 },
    { temp: 70, seccion_mm2: 126.7, kcmil: 250, A1: 195, B1: 248, E: 286 },
    { temp: 70, seccion_mm2: 150, A1: 216, B1: 262, E: 319 },
    { temp: 70, seccion_mm2: 152, kcmil: 300, A1: 217, B1: 264, E: 321 },
    { temp: 70, seccion_mm2: 177.3, kcmil: 350, A1: 239, B1: 289, E: 355 },
    { temp: 70, seccion_mm2: 185, A1: 245, B1: 296, E: 364 },
    { temp: 70, seccion_mm2: 202.7, kcmil: 400, A1: 259, B1: 315, E: 386 },
    { temp: 70, seccion_mm2: 240, A1: 286, B1: 346, E: 430 },
    { temp: 70, seccion_mm2: 253.3, kcmil: 500, A1: 296, B1: 356, E: 446 },
    { temp: 70, seccion_mm2: 300, A1: 328, B1: 394, E: 497 }],
    '90C': [{ temp: 90, seccion_mm2: 1.5, A1: 17, A2: 17, B1: 18, B2: 19, D1: 19, D2: 23, E: 19 },
    { temp: 90, seccion_mm2: 2.08, awg: 14, A1: 21, A2: 20, B1: 24, B2: 24, D1: 30, D2: 31, E: 28 },
    { temp: 90, seccion_mm2: 2.5, A1: 23, A2: 22, B1: 24, B2: 24, D1: 33, D2: 38, E: 32 },
    { temp: 90, seccion_mm2: 3.31, awg: 12, A1: 28, A2: 26, B1: 31, B2: 31, D1: 38, D2: 39, E: 38 },
    { temp: 90, seccion_mm2: 4, A1: 31, A2: 30, B1: 37, B2: 35, D1: 42, D2: 59, E: 42, F: 42 },
    { temp: 90, seccion_mm2: 5.26, awg: 10, A1: 37, A2: 35, B1: 39, B2: 38, D1: 48, D2: 69, E: 50, F: 50 },
    { temp: 90, seccion_mm2: 6, A1: 40, A2: 38, B1: 48, B2: 44, D1: 52, D2: 74, E: 54, F: 55 },
    { temp: 90, seccion_mm2: 8.37, awg: 8, A1: 49, A2: 46, B1: 59, B2: 54, D1: 63, D2: 89, E: 67, F: 68 },
    { temp: 90, seccion_mm2: 10, A1: 54, A2: 51, B1: 66, B2: 60, D1: 68, D2: 98, E: 75, F: 77 },
    { temp: 90, seccion_mm2: 13.3, awg: 6, A1: 65, A2: 61, B1: 79, B2: 72, D1: 80, D2: 114, E: 89, F: 93 },
    { temp: 90, seccion_mm2: 16, A1: 73, A2: 68, B1: 88, B2: 80, D1: 89, D2: 126, E: 100, F: 105 },
    { temp: 90, seccion_mm2: 21.1, awg: 4, A1: 86, A2: 80, B1: 105, B2: 95, D1: 103, D2: 147, E: 114, F: 126 },
    { temp: 90, seccion_mm2: 25, A1: 95, A2: 89, B1: 117, B2: 105, D1: 113, D2: 161, E: 127, F: 141 },
    { temp: 90, seccion_mm2: 26.7, awg: 3, A1: 99, A2: 92, B1: 122, B2: 109, D1: 117, D2: 167, E: 133, F: 147 },
    { temp: 90, seccion_mm2: 33.6, awg: 2, A1: 114, A2: 106, B1: 141, B2: 125, D1: 132, D2: 189, E: 154, F: 172 },
    { temp: 90, seccion_mm2: 35, A1: 117, A2: 109, B1: 144, B2: 128, D1: 136, D2: 194, E: 158, F: 176 },
    { temp: 90, seccion_mm2: 42.4, awg: 1, A1: 132, A2: 122, B1: 163, B2: 144, D1: 150, D2: 216, E: 178, F: 200 },
    { temp: 90, seccion_mm2: 50, A1: 141, A2: 130, B1: 175, B2: 154, D1: 159, D2: 230, E: 192, F: 216 },
    { temp: 90, seccion_mm2: 53.5, awg: "1/0", A1: 152, A2: 140, B1: 188, B2: 165, D1: 170, D2: 245, E: 207, F: 234 },
    { temp: 90, seccion_mm2: 67.4, awg: "2/0", A1: 175, A2: 161, B1: 217, B2: 190, D1: 192, D2: 278, E: 240, F: 273 },
    { temp: 90, seccion_mm2: 70, A1: 179, A2: 164, B1: 222, B2: 194, D1: 197, D2: 282, E: 246, F: 279 },
    { temp: 90, seccion_mm2: 85, awg: "3/0", A1: 201, A2: 185, B1: 251, B2: 218, D1: 218, D2: 315, E: 278, F: 318 },
    { temp: 90, seccion_mm2: 95, A1: 216, A2: 197, B1: 269, B2: 233, D1: 232, D2: 339, E: 298, F: 342 },
    { temp: 90, seccion_mm2: 107.2, awg: "4/0", A1: 232, A2: 212, B1: 290, B2: 251, D1: 248, D2: 362, E: 322, F: 371 },
    { temp: 90, seccion_mm2: 120, A1: 249, A2: 227, B1: 312, B2: 268, D1: 263, D2: 386, E: 346, F: 400 },
    { temp: 90, seccion_mm2: 126.7, kcmil: 250, A1: 257, A2: 234, B1: 322, B2: 277, D1: 270, D2: 396, E: 358, F: 415 },
    { temp: 90, seccion_mm2: 150, A1: 285, A2: 259, B1: 342, B2: 300, D1: 296, D2: 431, E: 399, F: 464 },
    { temp: 90, seccion_mm2: 152, kcmil: 300, A1: 287, A2: 261, B1: 344, B2: 302, D1: 299, D2: 437, E: 402, F: 468 },
    { temp: 90, seccion_mm2: 177.3, kcmil: 350, A1: 316, A2: 287, B1: 374, B2: 331, D1: 325, D2: 474, E: 444, F: 518 },
    { temp: 90, seccion_mm2: 185, A1: 324, A2: 295, B1: 384, B2: 340, D1: 332, D2: 486, E: 456, F: 533 },
    { temp: 90, seccion_mm2: 202.7, kcmil: 400, A1: 342, A2: 312, B1: 405, B2: 358, D1: 349, D2: 510, E: 483, F: 567 },
    { temp: 90, seccion_mm2: 240, A1: 380, A2: 346, B1: 450, B2: 398, D1: 382, D2: 563, E: 538, F: 634 },
    { temp: 90, seccion_mm2: 253.3, kcmil: 500, A1: 392, A2: 357, B1: 464, B2: 410, D1: 393, D2: 576, E: 557, F: 657 },
    { temp: 90, seccion_mm2: 300, A1: 435, A2: 396, B1: 514, B2: 455, D1: 431, D2: 629, E: 621, F: 736 }],
    'movil': [{ seccion_mm2: 0.5, E: 3 },
    { seccion_mm2: 0.75, E: 6 },
    { seccion_mm2: 1, E: 10 },
    { seccion_mm2: 1.5, E: 18.5 },
    { seccion_mm2: 2.08, awg: 14, E: 22 },
    { seccion_mm2: 2.5, E: 25 },
    { seccion_mm2: 3.31, awg: 12, E: 30 },
    { seccion_mm2: 4, E: 34 },
    { seccion_mm2: 5.26, awg: 10, E: 40 },
    { seccion_mm2: 6, E: 43 },
    { seccion_mm2: 8.37, awg: 8, E: 53 },
    { seccion_mm2: 10, E: 60 },
    { seccion_mm2: 13.3, awg: 6, E: 71 },
    { seccion_mm2: 16, E: 80 },
    { seccion_mm2: 21.1, awg: 4, E: 91 },
    { seccion_mm2: 25, E: 101 },
    { seccion_mm2: 26.7, awg: 3, E: 106 },
    { seccion_mm2: 33.6, awg: 2, E: 122 },
    { seccion_mm2: 35, E: 126 },
    { seccion_mm2: 42.4, awg: 1, E: 142 },
    { seccion_mm2: 50, E: 153 },
    { seccion_mm2: 53.5, awg: "1/0", E: 165 },
    { seccion_mm2: 67.4, awg: "2/0", E: 191 },
    { seccion_mm2: 70, E: 196 },
    { seccion_mm2: 85, awg: "3/0", E: 222 },
    { seccion_mm2: 95, E: 238 },
    { seccion_mm2: 107.2, awg: "4/0", E: 257 },
    { seccion_mm2: 120, E: 276 },
    { seccion_mm2: 126.7, kcmil: 250, E: 286 },
    { seccion_mm2: 150, E: 319 },
    { seccion_mm2: 152, kcmil: 300, E: 321 },
    { seccion_mm2: 177.3, kcmil: 350, E: 355 },
    { seccion_mm2: 185, E: 364 },
    { seccion_mm2: 202.7, kcmil: 400, E: 386 },
    { seccion_mm2: 240, E: 430 },
    { seccion_mm2: 253.3, kcmil: 500, E: 446 },
    { seccion_mm2: 300, E: 497 }],
};

export interface ConductorData {
    nombre: string;
    caracteristicas: string;
    uso: string;
    tempMax: string;
    tension: string;
    aislamiento: string;
    cubierta: string;
    tabla_ref: '70C' | '90C' | 'movil' | 'SinTabla';
}

export const metodosInstalacion = [
    { id: 'A1', label: 'Método A1: Conductores en ductos embutidos' },
    { id: 'A2', label: 'Método A2: Cables multiconductores en ductos embutidos' },
    { id: 'B1', label: 'Método B1: Conductores en ductos adosados' },
    { id: 'B2', label: 'Método B2: Cables multiconductores en ductos adosados' },
    { id: 'D1', label: 'Método D1: Cables en ductos enterrados' },
    { id: 'D2', label: 'Método D2: Cables directamente enterrados' },
    { id: 'E', label: 'Método E: Cables al aire libre / bandejas' },
    { id: 'F', label: 'Método F: Cables monoconductores al aire libre' },
];